source 'https://rubygems.org'

gem 'pieces'

gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'

group :development, :test do
  gem 'pry-byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

