source 'https://rubygems.org'

gem 'pieces', path: '../../../pieces'
gem 'bits-n-pieces', path: '../../../bits-n-pieces'

# For debugging
gem 'pry-byebug'

# For sprockets babel support
gem 'sprockets', github: 'rails/sprockets'
